#lang racket
(provide (all-defined-out))
(define green "Green - Weekly rate of less than 10 cases per 100,000 people and a positivity rate of less than one per cent")
(define yellow "Yellow - Weekly rate of 10 to 39.9 cases per 100,000 people and a positivity rate of one to 2.5 per cent")
(define orange "orange - Weekly incidence rate of 40 to 99.9 per 100,000 people and a positivity rate ranging from 2.5 to 9.9 per cent")
(define red "Red - Weekly incidence rate of more than 100 cases per 100,000 people and a positivity rate of more than 10 per cent")
(define gray "Gray- Lockdown")
(define currentState gray)


(define emergency "Call 911 Immediately")
(define link-to-test-center "https://covid-19.ontario.ca/assessment-centre-locations")
(define symptom "You have at least one common symptom of COVID-19. It is recommended to self-isolate and get tested. Opening browser to check nearest testing location...")
(define lstSchools '(
"F.W. Begley" 
,"A.V. Graham" 
,"Amherstburg" 
,"Anderdon"
,"Belle River DHS" 
,"Belle River PS"
,"Bellewood" 
,"Brock" 
,"Centennial Central"
,"Central"
,"Colchester N."
,"Coronation P.S."
,"D.M. Eagle"
,"David Suzuki"
,"Davis"
,"Dougall P.S"
,"East Mersea"
,"Essex DHS"
,"Essex P.S P.S"
,"Ford City"
,"Forest Glade"
,"General Amherst"
,"Giles Campus F.I"
,"Glenwood"
,"Gore Hill"
,"Gosfield North"
,"Harrow P.S."
,"Herman Academy"
,"Hetherington"
,"Highland Campus"
,"Hugh Beaton"
,"Jack Miner"
,"John Campbell"
,"Kennedy"
,"King EdwardKng Eward"
,"Kingsville HS HS"
,"Kingsville P.S"
,"Lakeshore Discovery"
,"LaSalle P.S"
,"Leamington DSS DSS"
,"M.D. BennieM.D."
,"Malden Central"
,"Marlborough"
,"Massey"
,"Maxwell"
,"McWilliam"
,"Mt Carmel-Blytheswood"
,"BrNorthwoodock"
,"P.A.S.S.- Amherstburg Campus"
,"P.A.S.S- Leamington Campus"
,"P.A.S.S- Mason Centre" 
,"Parkview"
,"Pelee Island"
,"Prince Andrew"
,"Princess Elizabeth"
,"Prince Edward"
,"Queen Elizabeth"
,"Queen Victoria"
,"Riverside"
,"Roseland"
,"Roseville"
,"Sandwich Secondary"
,"Sandwich West P.S."
,"Southwood"
,"Talbot Trail"
,"Tecumseh Vista"
,"Trillum Learning Centre"
,"Walkerville"
,"West Gate"
,"Western"
,"Westview Freedom Academy"))
